pipeline {
    
    options {
        timestamps()
    }

    agent {
        kubernetes {
            yamlFile 'jenkins/DataGovernance/KubernetesPod.yaml'
            defaultContainer 'jmeter'
        }
    }

    stages {
        stage('Configure JMeter') {
            steps {
                git branch: 'main', url: 'https://github.com/gtom-ping/perf-pingdata-lab'
                sh 'cp apache-jmeter/bin/* ${SERVER_BITS_DIR}/bin'
            }
        }

        stage('Wait for Product Availability') {
            steps {
                waitUntil {
					script {
            			response = httpRequest ignoreSslErrors: true, url: 'https://pingdatagovernance:443/available-or-degraded-state', validResponseCodes: '100:599'
						response.status == 200 || response.status == 503
					}
				}
            }
        }

        stage('Deny based on Access Token - Allow') {
            steps {
                sh '${SERVER_BITS_DIR}/bin/jmeter -n -f -t apache-jmeter/scripts/access-api.jmx -l access-api.csv -q apache-jmeter/scripts/test.properties'
                //perfReport errorFailedThreshold: 0, errorUnstableThreshold: 0, compareBuildPrevious: true, configType: 'PRT', graphType: 'PRT', modePerformancePerTestCase: true, modeThroughput: true, sourceDataFiles: 'access-api.csv'
                perfReport compareBuildPrevious: true, modeOfThreshold: true, modePerformancePerTestCase: true, modeThroughput: true, relativeUnstableThresholdNegative: 5.0, relativeUnstableThresholdPositive: 5.0, sourceDataFiles: 'access-api.csv'
            }
        }

        stage('Deny based on Access Token - Deny') {
            steps {
                sh '${SERVER_BITS_DIR}/bin/jmeter -n -f -t apache-jmeter/scripts/deny-api.jmx -l deny-api.csv -q apache-jmeter/scripts/test.properties'
                //perfReport errorFailedThreshold: 0, errorUnstableThreshold: 0, compareBuildPrevious: true, configType: 'PRT', graphType: 'PRT', modePerformancePerTestCase: true, modeThroughput: true, sourceDataFiles: 'deny-api.csv'
                perfReport compareBuildPrevious: true, modeOfThreshold: true, modePerformancePerTestCase: true, modeThroughput: true, relativeUnstableThresholdNegative: 5.0, relativeUnstableThresholdPositive: 5.0, sourceDataFiles: 'deny-api.csv'
            }
        }
    }
}