pipeline {
    agent {
        kubernetes {
            yamlFile 'jenkins/DataGovernance/KubernetesPod.yaml'
        }
    }

    stages {
        stage('Configure JMeter') {
            steps {
                container('jmeter') {
                    git branch: 'main', url: 'https://github.com/gtom-ping/perf-pingdata-lab'
                    sh 'cp jmeter-files/user.properties ${SERVER_ROOT_DIR}'
                    sh 'cp jmeter-files/jaas.conf ${SERVER_ROOT_DIR}'
                    sh 'cp jmeter-files/krb5.conf ${SERVER_ROOT_DIR}'
                }
            }
        }

        stage('Deny based on Access Token - Allow') {
            steps {
                container('jmeter') {
                    sh '${SERVER_ROOT_DIR}/bin/jmeter -n -f -t jmeter-files/access-api.jmx -l access-api.csv -q jmeter-files/test.properties'
                    perfReport compareBuildPrevious: true, configType: 'PRT', graphType: 'PRT', modePerformancePerTestCase: true, modeThroughput: true, sourceDataFiles: 'access-api.csv'
                }
            }
        }
        

        stage('Deny based on Access Token - Deny') {
            steps {
                container('jmeter') {
                    sh '${SERVER_ROOT_DIR}/bin/jmeter -n -f -t jmeter-files/deny-api.jmx -l deny-api.csv -q jmeter-files/test.properties'
                    perfReport compareBuildPrevious: true, configType: 'PRT', graphType: 'PRT', modePerformancePerTestCase: true, modeThroughput: true, sourceDataFiles: 'deny-api.csv'
                }
            }
        }
    }
}