pipeline {
    agent {
        kubernetes {
            yamlFile 'jenkins/DataGovernance/KubernetesPod.yaml'
        }
    }

    environment {
        THREADS=${THREADS}
        ITERATIONS=${ITERATIONS}
    }

    stages {
        stage('Configure JMeter') {
            steps {
                container('jmeter') {
                    git branch: 'main', url: 'https://github.com/gtom-ping/perf-pingdata-lab'
                    sh 'cp apache-jmeter/bin/* ${SERVER_BITS_DIR}/bin'
                }
            }
        }

        stage('Deny based on Access Token - Allow') {
            steps {
                container('jmeter') {
                    sh '${SERVER_BITS_DIR}/bin/jmeter -n -f -t apache-jmeter/scripts/access-api.jmx -l access-api.csv -q apache-jmeter/scripts/test.properties'
                    perfReport compareBuildPrevious: true, configType: 'PRT', graphType: 'PRT', modePerformancePerTestCase: true, modeThroughput: true, sourceDataFiles: 'access-api.csv'
                }
            }
        }
        

        stage('Deny based on Access Token - Deny') {
            steps {
                container('jmeter') {
                    sh '${SERVER_BITS_DIR}/bin/jmeter -n -f -t apache-jmeter/scripts/deny-api.jmx -l deny-api.csv -q apache-jmeter/scripts/test.properties'
                    perfReport compareBuildPrevious: true, configType: 'PRT', graphType: 'PRT', modePerformancePerTestCase: true, modeThroughput: true, sourceDataFiles: 'deny-api.csv'
                }
            }
        }
    }
}