apiVersion: v1

kind: Pod

metadata:
  name: dg-performance-pod
  labels:
    name: dg-performance-pod

spec:
  hostAliases:
    - ip: "127.0.0.1"
      hostnames:
        - "pingdatagovernance"
        - "pingdataconsole"
        - "jmeter"
        - "perf-service"
        - "upstream-api"

  imagePullSecrets:
  - name: gte-secret

  containers:
  - name: pingdatagovernance
    image: 574076504146.dkr.ecr.us-west-2.amazonaws.com/snapshot-builds/pingdatagovernance:latest
    # image: '574076504146.dkr.ecr.us-west-2.amazonaws.com/snapshot-builds/pingdatagovernance:8.3.0.0-SNAPSHOT-alpine-az11-20210112'
    # image: pingidentity/pingdatagovernance:latest
    imagePullPolicy: Always
    env: 
      - name: SERVER_PROFILE_URL
        # value: https://github.com/pingidentity/pingidentity-server-profiles.git
        value: https://github.com/gtom-ping/perf-pingdata-lab.git
      - name: SERVER_PROFILE_PATH
        # value: perf-testing/pingdatagovernance
        value: pingidentity-server-profiles/pingdatagovernance
      - name: PING_IDENTITY_ACCEPT_EULA
        value: "YES"
    envFrom:
      - secretRef:
          name: devops-secret
          optional: true
    ports:
      - containerPort: 80
      - containerPort: 443
      - containerPort: 636
    resources:
      limits:
        memory: 4Gi
        cpu: "4"

  - name: upstream-api
    image: samirgandhi/dg-qa-upstream-api
    ports:
      - containerPort: 3000
    resources:
      limits:
        memory: 2Gi
        cpu: "2"

  # - name: perf-service
  #   image: pingcloud-docker.jfrog.io/pingidentity/perf-service:latest
  #   ports:
  #     - containerPort: 8080
  #   resources:
  #     limits: 
  #       memory: 1.5Gi
  #       cpu: "1.5"

  - name: jmeter
    image: pingidentity/apache-jmeter:latest
    env:
      - name: SERVER_PROFILE_URL
        value: https://github.com/gtom-ping/perf-pingdata-lab.git
      - name: SERVER_PROFILE_PATH
        value: jmeter-files
      - name: MAX_HEAP_SIZE
        value: 1g
    tty: true
    command:
      - "cat"
    resources:
      limits:
        memory: 4Gi
        cpu: "4"

  # - name: pingdataconsole
  #   image: pingidentity/pingdataconsole:edge
  #   ports:
  #     - containerPort: 8443 
  #   resources:
  #     limits:
  #       memory: 1Gi
  #       cpu: "1"